"""empty message

Revision ID: 115b584a6fcb
Revises: 6a2f69ee8d84
Create Date: 2023-08-03 16:02:47.691508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115b584a6fcb'
down_revision = '6a2f69ee8d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_test', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('last_time')

    # ### end Alembic commands ###
