"""empty message

Revision ID: 48aca6811f84
Revises: 
Create Date: 2023-06-27 10:51:36.815989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48aca6811f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_fung',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('create_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_user_id'], ['user_fung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index('apps_id_uindex')

    op.drop_table('apps')
    op.drop_table('request')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='编号自增'),
    sa.Column('keyCode', mysql.VARCHAR(length=200), nullable=False, comment='项目唯一编号'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False, comment='中文项目名'),
    sa.Column('desc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500), server_default=sa.text("''"), nullable=False, comment='描述'),
    sa.Column('status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='状态'),
    sa.Column('operator', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50), nullable=False, comment='操作者'),
    sa.Column('update', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目产品表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='项目产品表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True, comment='提测标题'),
    sa.Column('appId', mysql.VARCHAR(length=50), nullable=True, comment='应用服务'),
    sa.Column('developer', mysql.VARCHAR(length=255), nullable=True, comment='提测RD'),
    sa.Column('tester', mysql.VARCHAR(length=255), nullable=True, comment='测试QA'),
    sa.Column('CcMail', mysql.VARCHAR(length=500), nullable=True, comment='关系人'),
    sa.Column('version', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=True, comment='提测版本'),
    sa.Column('type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='提测类型 1.功能 2.性能 3.安全'),
    sa.Column('scope', mysql.TEXT(), nullable=True, comment='测试说明'),
    sa.Column('gitCode', mysql.VARCHAR(length=200), nullable=True, comment='项目代码'),
    sa.Column('wiki', mysql.VARCHAR(length=200), nullable=True, comment='产品文档'),
    sa.Column('more', mysql.TEXT(), nullable=True, comment='是否发送邮件，0未操作，1成功，2失败'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='测试状态 1-已提测 2-测试中 3-通过 4-失败 9-废弃'),
    sa.Column('sendEmail', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否发送消息，0未操作，1成功，2失败'),
    sa.Column('isDel', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='状态0正常1删除'),
    sa.Column('createUser', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='创建人'),
    sa.Column('createDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updateUser', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='修改人'),
    sa.Column('updateDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='修改时间'),
    sa.Column('test_desc', mysql.VARCHAR(length=2000), server_default=sa.text("''"), nullable=True, comment='结论描述'),
    sa.Column('test_risks', mysql.VARCHAR(length=2000), server_default=sa.text("''"), nullable=True, comment='风险提示'),
    sa.Column('test_cases', mysql.VARCHAR(length=2000), server_default=sa.text("''"), nullable=True, comment='测试用例描述'),
    sa.Column('test_bugs', mysql.VARCHAR(length=1000), server_default=sa.text("''"), nullable=True, comment='缺陷列表'),
    sa.Column('test_file', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='附件文件地址'),
    sa.Column('test_note', mysql.VARCHAR(length=1000), server_default=sa.text("''"), nullable=True, comment='报告备注'),
    sa.Column('test_email', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否发送消息，0未操作，1成功，2失败'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apps',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('appId', mysql.VARCHAR(length=50), nullable=True, comment='应用服务ID'),
    sa.Column('productId', mysql.BIGINT(), autoincrement=False, nullable=True, comment='外键关联产品所属'),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True, comment='应用描述'),
    sa.Column('tester', mysql.VARCHAR(length=300), nullable=True, comment='测试负责人'),
    sa.Column('developer', mysql.VARCHAR(length=300), nullable=True, comment='默认研发负责人'),
    sa.Column('producer', mysql.VARCHAR(length=300), nullable=True, comment='默认产品经理'),
    sa.Column('CcEmail', mysql.VARCHAR(length=500), nullable=True, comment='默认抄送邮件或组'),
    sa.Column('gitCode', mysql.VARCHAR(length=200), nullable=True, comment='代码地址'),
    sa.Column('wiki', mysql.VARCHAR(length=200), nullable=True, comment='项目说明地址'),
    sa.Column('more', mysql.TEXT(), nullable=True, comment='更多的信息'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='提测状态：1-已提测 2-测试中 3-通过 4-失败 9-废弃'),
    sa.Column('isDel', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='状态0正常1删除'),
    sa.Column('createUser', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True, comment='创建人'),
    sa.Column('createDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updateUser', mysql.VARCHAR(length=20), nullable=True, comment='修改人'),
    sa.Column('updateDate', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='应用管理',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='应用管理',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index('apps_id_uindex', ['id'], unique=False)

    op.drop_table('project')
    op.drop_table('user_fung')
    # ### end Alembic commands ###
