"""empty message

Revision ID: 6a2f69ee8d84
Revises: 48aca6811f84
Create Date: 2023-08-01 16:48:15.050082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2f69ee8d84'
down_revision = '48aca6811f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('methods', sa.String(length=100), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_test')
    # ### end Alembic commands ###
